using Microsoft.Extensions.Primitives;

namespace Zooyard.Configuration;

/// <summary>
/// Provides an implementation of IProxyConfigProvider to support config being generated by code.
/// </summary>
public sealed class InMemoryConfigProvider : IRpcConfigProvider
{
    // Marked as volatile so that updates are atomic
    private volatile InMemoryConfig _config;

    /// <summary>
    /// Creates a new instance.
    /// </summary>
    public InMemoryConfigProvider(IReadOnlyList<RouteConfig> routes, IReadOnlyList<ServiceConfig> services)
        : this(routes, services, Guid.NewGuid().ToString())
    { }

    /// <summary>
    /// Creates a new instance, specifying a revision id of the configuration.
    /// </summary>
    public InMemoryConfigProvider(IReadOnlyList<RouteConfig> routes, IReadOnlyList<ServiceConfig> services, string revisionId)
    {
        _config = new InMemoryConfig(routes, services, revisionId);
    }

    /// <summary>
    /// Implementation of the IProxyConfigProvider.GetConfig method to supply the current snapshot of configuration
    /// </summary>
    /// <returns>An immutable snapshot of the current configuration state</returns>
    public IRpcConfig GetConfig() => _config;

    /// <summary>
    /// Swaps the config state with a new snapshot of the configuration, then signals that the old one is outdated.
    /// </summary>
    public void Update(IReadOnlyList<RouteConfig> routes, IReadOnlyList<ServiceConfig> services)
    {
        var newConfig = new InMemoryConfig(routes, services);
        UpdateInternal(newConfig);
    }

    /// <summary>
    /// Swaps the config state with a new snapshot of the configuration, then signals that the old one is outdated.
    /// </summary>
    public void Update(IReadOnlyList<RouteConfig> routes, IReadOnlyList<ServiceConfig> services, string revisionId)
    {
        var newConfig = new InMemoryConfig(routes, services, revisionId);
        UpdateInternal(newConfig);
    }

    private void UpdateInternal(InMemoryConfig newConfig)
    {
        var oldConfig = Interlocked.Exchange(ref _config, newConfig);
        oldConfig.SignalChange();
    }

    /// <summary>
    /// Implementation of IProxyConfig which is a snapshot of the current config state. The data for this class should be immutable.
    /// </summary>
    private class InMemoryConfig : IRpcConfig
    {
        // Used to implement the change token for the state
        private readonly CancellationTokenSource _cts = new ();

        public InMemoryConfig(IReadOnlyList<RouteConfig> routes, IReadOnlyList<ServiceConfig> services)
            : this(routes, services, Guid.NewGuid().ToString())
        { }

        public InMemoryConfig(IReadOnlyList<RouteConfig> routes, IReadOnlyList<ServiceConfig> services, string revisionId)
        {
            RevisionId = revisionId ?? throw new ArgumentNullException(nameof(revisionId));
            Routes = routes;
            Services = services;
            ChangeToken = new CancellationChangeToken(_cts.Token);
        }

        /// <inheritdoc/>
        public string RevisionId { get; }

        /// <summary>
        /// A snapshot of the list of routes for the proxy
        /// </summary>
        public IReadOnlyList<RouteConfig> Routes { get; }

        /// <summary>
        /// A snapshot of the list of Clusters which are collections of interchangable destination endpoints
        /// </summary>
        public IReadOnlyList<ServiceConfig> Services { get; }

        /// <summary>
        /// Fired to indicate the the proxy state has changed, and that this snapshot is now stale
        /// </summary>
        public IChangeToken ChangeToken { get; }

        internal void SignalChange()
        {
            _cts.Cancel();
        }
    }
}