# 工作流的名称
name: .NET Build

# 触发工作流的事件
on:
  # 当代码推送到主分支时触发
  push:
    branches:
      - main
  # 手动触发工作流
  workflow_dispatch:

# 工作流中的作业
jobs:
  build:
    # 运行作业的环境
    runs-on: ubuntu-latest

    # 作业中的步骤
    steps:
      # 检出代码到工作目录
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 .NET SDK 版本
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          # 指定要使用的 .NET SDK 版本
          dotnet-version: '8.0.x'

      # 恢复项目依赖项
      - name: Restore dependencies
        run: dotnet restore

      # 构建项目
      - name: Build
        run: dotnet build --no-restore

      # 发布项目（可选）
      - name: Publish
        run: dotnet publish -c Release --no-build -o ${{ github.workspace }}/publish
